DROP TABLE "<SCHEMA>"."TESTS";

CREATE TABLE "<SCHEMA>"."TESTS"
(
	"ID" NUMBER(5,0), 
	"TEST" VARCHAR2(100)
);

INSERT INTO "<SCHEMA>"."TESTS" (ID, TEST) VALUES (1, 'TEST TEST TEST');

COMMIT;

SELECT TEST FROM TEMPLATE;

CREATE OR REPLACE PROCEDURE dummy_proc (p_test IN VARCHAR2, p_cur OUT SYS_REFCURSOR ) 
AS 
BEGIN
   OPEN p_cur FOR SELECT TEST FROM TESTS WHERE TEST LIKE p_test;
END dummy_proc;
